const { StyleSheet } = require('react-native');

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#f8f9ff', height: '100%' },
  header: {
    paddingTop: 80,
    paddingHorizontal: 20,
    paddingBottom: 30,
    height: 250,
  },
  headerTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 15,
  },
  question: { color: '#fff', fontSize: 14, fontFamily: 'Poppins-Regular' },
  getStarted: {
    color: '#fff',
    fontFamily: 'Poppins-SemiBold',
    backgroundColor: '#ffffff30',
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderRadius: 20,
    fontSize: 13,
  },
  title: {
    fontSize: 32,
    color: '#fff',
    fontFamily: 'Poppins-SemiBold',
    alignSelf: 'center',
  },
  card: {
    backgroundColor: '#fff',
    marginTop: -100,
    marginHorizontal: 10,
    borderRadius: 25,
    padding: 20,
    elevation: 2,
  },
  signupCard: {
    backgroundColor: '#fff',
    marginTop: -120,
    marginHorizontal: 10,
    borderRadius: 25,
    padding: 20,
    elevation: 2,
    zIndex: 999,
  },
  welcome: {
    fontSize: 22,
    fontFamily: 'Poppins-SemiBold',
    color: '#333',
    marginBottom: 5,
  },
  subtitle: {
    fontSize: 14,
    color: '#666',
    marginBottom: 10,
    fontFamily: 'Poppins-Regular',
  },
  imageContainer: {
    height: 140,
    width: 140,
    backgroundColor: 'white',
    alignSelf: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 100,
    elevation: 2,
    marginBottom: 20,
  },
  inputWrapper: {
    marginBottom: 15,
  },
  label: {
    fontSize: 13,
    color: '#555',
    marginBottom: 5,
    fontFamily: 'Poppins-Regular',
  },
  inputContainer: {
    width: 120,
    alignSelf: 'center',
  },
  input: {
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 14,
    fontFamily: 'Poppins-Regular',
  },
  otpInput: {
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 10,
    fontSize: 14,
    fontFamily: 'Poppins-Regular',
  },
  passwordRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  signInButton: {
    marginTop: 10,
    borderRadius: 12,
    overflow: 'hidden',
  },
  signInGradient: {
    paddingVertical: 14,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 12,
  },
  signInText: {
    color: '#fff',
    fontFamily: 'Poppins-SemiBold',
    fontSize: 14,
  },
  forgot: {
    textAlign: 'center',
    marginVertical: 10,
    color: '#666',
    fontSize: 13,
    fontFamily: 'Poppins-Regular',
  },
  or: {
    textAlign: 'center',
    color: '#aaa',
    fontSize: 12,
    marginVertical: 10,
  },
  socialRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 10,
  },
  socialButton: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#ddd',
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 10,
    flex: 1,
    justifyContent: 'center',
    marginHorizontal: 5,
  },
  socialText: {
    marginLeft: 8,
    fontSize: 14,
    color: '#333',
    fontFamily: 'Poppins-Regular',
  },
  keyContainer: {
    flex: 1,
    zIndex: 999,
  },
  picker: {
    height: 50,
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 10,
    backgroundColor: '#fff',
  },
});

export default styles;
